name: 'Homebrew Releaser'
description: 'Release scripts, binaries, and executables directly to Homebrew via GitHub Actions.'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  homebrew_owner:
    description: 'The name of the homebrew tap owner to publish your formula to as it appears on GitHub.'
    required: true
    default: ''
  homebrew_tap:
    description: 'The name of the homebrew tap to publish your formula to as it appears on GitHub.'
    required: true
    default: ''
  formula_folder:
    description: 'The name of the folder in your homebrew tap where formula will be committed to.'
    required: false
    default: Formula
  branch:
    description: The branch to push your formula file to (if not present, the branch used will be your repo default branch).
    required: false
  github_token:
    description: 'The GitHub Token (saved as a repo secret) that has `repo` permissions for the homebrew tap you want to release to.'
    required: true
  commit_owner:
    description: 'Git author info used to commit to the homebrew tap.'
    required: false
    default: homebrew-releaser
  commit_email:
    description: 'Git author info used to commit to the homebrew tap.'
    required: false
    default: homebrew-releaser@example.com
  depends_on:
    description: 'Custom dependencies in case other formulas are needed to build the current one (can be multiline).'
    required: false
  install:
    description: 'Custom install command for your formula.'
    required: true
  test:
    description: 'Custom test command for your formula so you can run `brew test`.'
    required: false
  download_strategy:
    description: 'The Homebrew download strategy to use for formulas.'
    required: false
  custom_require:
    description: 'Allows you to add a custom require_relative at the top of the formula template.'
    required: false
  formula_includes:
    description: 'Allows you to add custom includes inside the formula class, before dependencies and install blocks.'
    required: false
  update_python_resources:
    description: "Run 'brew update-python-resources' on the formula to add Python resources."
    required: false
    default: 'false'
  version:
    description: 'Override the automatically detected version of a formula with an explicit value.'
    required: false
  target_darwin_amd64:
    description: 'Add a custom URL/checksum target for AMD64 Darwin builds.'
    required: false
  target_darwin_arm64:
    description: 'Add a custom URL/checksum target for ARM64 Darwin builds.'
    required: false
  target_linux_amd64:
    description: 'Add a custom URL/checksum target for AMD64 Linux builds.'
    required: false
  target_linux_arm64:
    description: 'Add a custom URL/checksum target for ARM64 Linux builds.'
    required: false
  custom_tarball:
    description: 'Use a custom tarball on your release instead of the auto generated or templated arch URLs listed above.'
    required: false
  update_readme_table:
    description: "Update your homebrew tap's README with a table of all projects in the tap."
    required: false
    default: 'false'
  skip_commit:
    description: 'Skips committing the generated formula to a homebrew tap (useful for local testing).'
    required: false
    default: 'false'
  skip_checksum:
    description: 'Skips uploading the checksum file for release assets to the release.'
    required: false
    default: 'false'
  debug:
    description: 'Logs debugging info to console.'
    required: false
    default: 'false'
  ignore_warnings:
    description: 'Ignores non-critical warnings by not raising them at the end and failing the action.'
    required: false
    default: 'false'
runs:
  using: docker
  image: docker://justintime50/homebrew-releaser:3.2.1
  args:
    - ${{ inputs.homebrew_owner }}
    - ${{ inputs.homebrew_tap }}
    - ${{ inputs.formula_folder }}
    - ${{ inputs.branch }}
    - ${{ inputs.github_token }}
    - ${{ inputs.commit_owner }}
    - ${{ inputs.commit_email }}
    - ${{ inputs.depends_on }}
    - ${{ inputs.install }}
    - ${{ inputs.test }}
    - ${{ inputs.download_strategy }}
    - ${{ inputs.custom_require }}
    - ${{ inputs.formula_includes }}
    - ${{ inputs.update_python_resources }}
    - ${{ inputs.version }}
    - ${{ inputs.target_darwin_amd64 }}
    - ${{ inputs.target_darwin_arm64 }}
    - ${{ inputs.target_linux_amd64 }}
    - ${{ inputs.target_linux_arm64 }}
    - ${{ inputs.custom_tarball }}
    - ${{ inputs.update_readme_table }}
    - ${{ inputs.skip_commit }}
    - ${{ inputs.skip_checksum }}
    - ${{ inputs.debug }}
    - ${{ inputs.ignore_warnings }}
