name: "Homebrew Releaser"
description: "Release scripts, binaries, and executables directly to Homebrew via GitHub Actions."
branding:
  icon: "package"
  color: "orange"
inputs:
  homebrew_owner:
    description: "The name of the homebrew tap owner to publish your formula to as it appears on GitHub."
    required: true
  homebrew_tap:
    description: "The name of the homebrew tap to publish your formula to as it appears on GitHub."
    required: true
  formula_folder:
    description: "The name of the folder in your homebrew tap where formula will be committed to."
    required: true
    default: "formula"
  github_token:
    description: "The GitHub Token (saved as a repo secret) that has `repo` permissions for the homebrew tap you want to release to."
    required: true
  commit_owner:
    description: "Git author info used to commit to the homebrew tap."
    required: false
    default: "homebrew-releaser@example.com"
  commit_email:
    description: "Git author info used to commit to the homebrew tap."
    required: false
    default: "homebrew-releaser@example.com"
  depends_on:
    description: "Custom dependencies in case other formulas are needed to build the current one (can be multiline)."
    required: false
  install:
    description: "Custom install command for your formula."
    required: true
  test:
    description: "Custom test command for your formula so you can run `brew test`."
    required: false
  download_strategy:
    description: "The Homebrew download strategy to use for formulas."
    required: false
  custom_require:
    description: "Allows you to add a custom require_relative at the top of the formula template."
    required: false
  version:
    description: "Override the automatically detected version of a formula with an explicit value."
    required: false
  target_darwin_amd64:
    description: "Add a custom URL/checksum target for AMD64 Darwin builds."
    required: false
  target_darwin_arm64:
    description: "Add a custom URL/checksum target for ARM64 Darwin builds."
    required: false
  target_linux_amd64:
    description: "Add a custom URL/checksum target for AMD64 Linux builds."
    required: false
  target_linux_arm64:
    description: "Add a custom URL/checksum target for ARM64 Linux builds."
    required: false
  update_readme_table:
    description: "Update your homebrew tap's README with a table of all projects in the tap."
    required: false
  skip_commit:
    description: "Skips committing the generated formula to a homebrew tap (useful for local testing)."
    required: false
  debug:
    description: "Logs debugging info to console."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.homebrew_owner }}
    - ${{ inputs.homebrew_tap }}
    - ${{ inputs.formula_folder }}
    - ${{ inputs.github_token }}
    - ${{ inputs.commit_owner }}
    - ${{ inputs.commit_email }}
    - ${{ inputs.install }}
    - ${{ inputs.test }}
    - ${{ inputs.target_darwin_amd64 }}
    - ${{ inputs.target_darwin_arm64 }}
    - ${{ inputs.target_linux_amd64 }}
    - ${{ inputs.target_linux_arm64 }}
    - ${{ inputs.update_readme_table }}
    - ${{ inputs.skip_commit }}
    - ${{ inputs.debug }}
