name: "Homebrew Releaser"
description: "Release scripts, binaries, and executables directly to Homebrew via GitHub Actions."
inputs:
  owner:
    description: "GitHub owner (username)"
    required: true
  owner_email:
    description: "Email of the GitHub user (for commit config, if you'd rather not specify an email, homebrew-releaser@example.com will be used)"
    required: false
    default: "homebrew-releaser@example.com"
  repo:
    description: "Name of the repository as it appears on GitHub"
    required: true
  install:
    description: "The Homebrew command to copy your script to bin"
    required: true
  test:
    description: "The Homebrew command to test your formula (optional field, if no test input is provided, no test block will be generated)"
    required: false
  homebrew_tap:
    description: "The name of the homebrew tap as it appears on GitHub"
    required: true
  homebrew_formula_folder:
    description: "The directory where your formula reside in your tap repo"
    required: true
  github_token:
    description: "The GitHub Token secret that has repo permissions to the repo you want to release to"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.owner_email }}
    - ${{ inputs.repo }}
    - ${{ inputs.install }}
    - ${{ inputs.test }}
    - ${{ inputs.homebrew_tap }}
    - ${{ inputs.homebrew_formula_folder }}
    - ${{ inputs.github_token }}
