name: 'Shell Releaser'
description: 'Release shell scripts directly to Homebrew via GitHub Actions.'
inputs:
  owner:
    description: 'GitHub owner (username)'
    required: true
  owner_email:
    description: 'GitHub owner email'
    required: true
  repo:
    description: 'GitHub repo name'
    required: true
  bin_install:
    description: 'The Homebrew command to install the script to bin'
    required: true
  homebrew_tap:
    description: 'The url for the GitHub Homebrew tap'
    required: true
  homebrew_formula_folder:
    description: 'The folder in the GitHub Homebrew tap that houses the formula'
    required: true
  github_token:
    description: 'The GitHub token with `repo` permission used to push updates to the Homebrew tap'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.owner_email }}
    - ${{ inputs.repo }}
    - ${{ inputs.bin_install }}
    - ${{ inputs.homebrew_tap }}
    - ${{ inputs.homebrew_formula_folder }}
    - ${{ inputs.github_token }}
