# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class TestFormulaTemplateEmptyFields < Formula
  desc ""
  homepage "https://github.com/Justintime50/test-formula-template-empty-fields"
  url "https://github.com/Justintime50/test-formula-template-empty-fields/archive/v0.1.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license ""

  def install
    bin.install "src/secure-browser-kiosk.sh" => "secure-browser-kiosk"
  end
end
