# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class TestGenerateFormulaMultilineTest < Formula
  desc "Release scripts, binaries, and executables to github"
  homepage "https://github.com/Justintime50/test-generate-formula-multiline-test"
  url "https://github.com/Justintime50/test-generate-formula-multiline-test/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"

  depends_on "bash" => :build
  depends_on "gcc"

  def install
    bin.install "src/secure-browser-kiosk.sh" => "secure-browser-kiosk"
  end

  test do
    output = shell_output(%Q(
      for test_case in case1 case2 case3; do
        run_case $test_case
      done
    ))
    assert_match("my script output", output)
  end
end
